name: Main
on: push

jobs:
  debug-build:
    runs-on: ubuntu-latest
    steps:
      - name: Install the latest nightly of the Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          target: x86_64-unknown-linux-musl
      - uses: actions/checkout@v4

  test:
    runs-on: ubuntu-latest
    needs:
      - debug-build
    steps:
      - uses: actions/checkout@v4

  release-build:
    runs-on: ubuntu-latest
    steps:
      - name: Install the latest nightly of the Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          target: x86_64-unknown-linux-musl
      - uses: actions/checkout@v4

  package:
    runs-on: ubuntu-latest
    needs:
      - release-build
    steps:
      - uses: actions/checkout@v4

  deploy:
    runs-on: ubuntu-latest
    needs:
      - test
      - package
    steps:
      - uses: actions/checkout@v4
